import {env} from 'cloudflare:workers';
import {Shell} from '@/components/site-shell';
import {isRecruiter} from '@/lib/admin';
import {chatGPTSignInPath} from '@/app/chatgpt-auth';
import {getJob} from '@/lib/jobs';
export const dynamic='force-dynamic';
export const metadata={title:'Recruiter access',robots:{index:false,follow:false}};
export default async function Recruiter(){if(!await isRecruiter())return <Shell><section className="page-content"><div className="prose"><h2>Recruiter access</h2><p>This area is restricted to the authorised Lawsearch recruitment account.</p><a className="button" style={{marginTop:25}} href={chatGPTSignInPath('/recruiter')} target="_top">Sign in with ChatGPT</a></div></section></Shell>;
try{if(!env.DB)throw new Error('Storage unavailable');const {results}=await env.DB.prepare('SELECT id,name,email,phone,sector,location,job_id,message,filename,created_at FROM applications ORDER BY created_at DESC LIMIT 100').all<{id:string,name:string,email:string,phone:string,sector:string,location:string,job_id:string,message:string,filename:string,created_at:number}>();return <Shell><section className="page-hero"><p className="eyebrow gold">LAWSEARCH RECRUITMENT</p><h1>Candidate applications.</h1><p>Latest 100 submissions. CV downloads are restricted to the authorised recruitment account.</p></section><section className="page-content">{results.length?<div className="table-wrap"><table><thead><tr><th>Received</th><th>Candidate</th><th>Contact</th><th>Interest</th><th>Notes & CV</th></tr></thead><tbody>{results.map(a=><tr key={a.id}><td>{new Date(a.created_at).toLocaleDateString('en-GB')}<br/>{a.id.slice(0,8).toUpperCase()}</td><td>{a.name}<br/>{a.location}</td><td><a href={`mailto:${a.email}`}>{a.email}</a><br/>{a.phone}</td><td>{a.sector}<br/>{getJob(a.job_id)?.title||'General registration'}</td><td><p style={{whiteSpace:'pre-wrap',maxWidth:300}}>{a.message}</p><a href={`/api/cv/${a.id}`}>Download {a.filename}</a></td></tr>)}</tbody></table></div>:<div className="empty"><h2>No applications yet.</h2><p>New submissions will appear here after candidates send their CV.</p></div>}</section></Shell>}catch(error){console.error('Recruiter inbox unavailable',error);return <Shell><section className="page-content"><p className="error">Applications are temporarily unavailable. Please try again later.</p></section></Shell>}}
