export const specialisms=['Property','Private Client','Family Law','Criminal Defence','Corporate','Commercial'];
export const jobs=[
{id:'ls-015',title:'Conveyancing / Residential Property Lawyer',sector:'Property',location:'Clifton · Bristol / North Petherton',salary:'Salary to be discussed',work:'Working pattern to be confirmed',summary:'A residential property opportunity for a conveyancing professional local to Clifton or North Petherton, with a manageable commute to the office.',details:['Office options in Clifton, Bristol, or North Petherton.','Candidates should be local to their preferred office or within a reasonable commuting distance.','Salary, qualification and experience requirements to be confirmed with Lawsearch.','Contact Lawsearch to discuss the residential property role, team and working arrangements.'],featured:true},
{id:'ls-016',title:'Experienced Contentious Probate Solicitor',sector:'Private Client',location:'Office location to be agreed',salary:'Salary to be discussed',work:'Working pattern to be confirmed',summary:'An opportunity for an experienced contentious probate solicitor to grow this area of practice and, in time, develop a team.',details:['Experienced contentious probate solicitor required to grow the firm’s work in this area.','Opportunity to develop a team over time.','Office location is open to discussion, provided you live locally to one of the firm’s offices and have a manageable commute.','Salary and working arrangements to be discussed.','Contact Lawsearch to discuss office options, your experience and the opportunity.'],featured:true},
{id:'ls-017',title:'Experienced Court of Protection Solicitor',sector:'Private Client',location:'Office location to be agreed',salary:'Salary to be discussed',work:'Working pattern to be confirmed',summary:'An opportunity for an experienced Court of Protection solicitor to grow the firm’s practice in this area.',details:['Experienced Court of Protection solicitor required to develop and grow the firm’s work in this area.','Office location is open to discussion, provided you live locally to one of the firm’s offices and have a manageable commute.','Salary and working arrangements to be discussed.','Contact Lawsearch to discuss office options, your experience and the opportunity.'],featured:true},
{id:'ls-012',title:'NQ Property Solicitor — Residential & Commercial',sector:'Property',location:'London',salary:'£35,000–£40,000',work:'Office based',summary:'A progressive London opportunity for a newly qualified solicitor working across residential and commercial property, with a performance-related bonus scheme.',details:['£35,000–£40,000 base salary.','Office-based role in London.','Newly qualified solicitor working across residential and commercial property.','A progressive role with a bonus scheme offering potential total earnings of up to £100,000, subject to performance and the scheme’s terms; this is not a guaranteed salary.','Contact Lawsearch to discuss the caseload, progression and bonus structure.'],featured:true},
{id:'ls-013',title:'Senior Property Solicitor',sector:'Property',location:'London',salary:'£50,000–£65,000',work:'Working pattern to be confirmed',summary:'A progressive senior property solicitor opportunity in London, supported by an experienced senior partnership team and an attractive bonus scheme.',details:['£50,000–£65,000 base salary.','At least five years’ PQE in property law.','London-based opportunity with an experienced senior partnership team.','Bonus scheme alongside the base salary.','Contact Lawsearch to discuss progression, the property caseload and working arrangements.'],featured:true},
{id:'ls-014',title:'Head of Residential Conveyancing',sector:'Property',location:'Romford',salary:'Up to £70,000',work:'Working pattern to be confirmed',summary:'Lead a residential conveyancing department in Romford, bringing substantial post-qualification experience and a background in team or department management.',details:['Base salary up to £70,000.','Romford-based head of department opportunity in residential conveyancing.','At least five years’ PQE.','Experience managing a team or previously leading a department.','Contact Lawsearch to discuss the team, leadership responsibilities and working arrangements.'],featured:true},
{id:'ls-001',title:'Senior Private Client Solicitor',sector:'Private Client',location:'Cirencester · Cotswolds',salary:'£70,000–£75,000',work:'Flexible working · discuss with us',summary:'A senior opportunity with an established Cotswolds practice. Discuss the team, caseload and full package in a confidential conversation.',details:['Senior private client appointment.','£70,000–£75,000 base salary plus bonus.','Full benefits and working pattern confirmed before introduction.'],featured:true},
{id:'ls-002',title:'Criminal Defence Solicitor',sector:'Criminal Defence',location:'Manchester',salary:'£40,000–£50,000',work:'Working pattern to be confirmed',summary:'Explore a criminal defence opportunity in Manchester through a personal, confidential introduction.',details:['£40,000–£50,000 depending on experience.','Discuss caseload, duty requirements and working pattern with Lawsearch.','Your CV is shared with an employer only after an agreed introduction.'],featured:true},
...['Manchester','London','Nottingham','Leicester','Trowbridge'].map((location,i)=>({id:`ls-00${i+3}`,title:'Residential Conveyancer',sector:'Property',location,salary:'£45,000–£60,000',work:'Working pattern varies by firm',summary:`Residential conveyancing opportunities in ${location}. Tell us about your experience and preferred working arrangements.`,details:['For residential conveyancing professionals seeking their next move.','£45,000–£60,000 advertised range across the current brief; individual packages vary.','Qualification requirements, caseload, support and hybrid arrangements confirmed for each individual role.'],featured:i===0})),
{id:'ls-008',title:'Licensed Conveyancer',sector:'Property',location:'Morden · London',salary:'£45,000–£50,000',work:'Hybrid · 4 office / 1 remote',summary:'A Morden-based opportunity offering a fee-earning bonus and one remote day each week.',details:['£45,000–£50,000 depending on experience.','Four days in the Morden office, one remote day.','Fee-earning bonus in addition to salary.','An initial Teams interview can be discussed.'],featured:false}];
export function getJob(id:string){return jobs.find(j=>j.id===id)}
